### ISSUE TITLE
Stop Ellis in a more targeted way

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/ellis#107]
At present we stop Ellis by sending SIGTERM to all processes using it's python executable. This can kill  processes it does not mean to. 

The reason we do this is because Ellis spawns multiple worker processes and we want to kill them all. It would be better for the main process to hook SIGTERM (plus other signals like SIGINT, SIGQUIT and SIGABRT?) and send this to all its children. We can the use a pidfile to make start-stop-daemon kill only the root server process.

**Comment by rkd-msw** [comment]
Feels like the approach in https://github.com/Metaswitch/crest/pull/260 fixes this?

**Comment by rkd-msw** [comment]
Fixed by https://github.com/Metaswitch/ellis/pull/145.
