### ISSUE TITLE
Ellis generates nginx configuration with duplicate server names.

### ISSUE THREAD

**Issue by chris-elford-metaswitch** [Metaswitch/ellis#170]
#### Symptoms

A user on the mailing list saw that nginx was failing to start up on an AIO OVF. He saw the following logs:

2016/04/03 13:36:21 [warn] 17281#0: conflicting server name "10.0.0.4" on [::]:80, ignored
2016/04/03 13:36:21 [warn] 17281#0: conflicting server name "10.0.0.4" on [::]:80, ignored
2016/04/03 13:36:21 [emerg] 17281#0: could not build the server_names_hash, you should increase server_names_hash_bucket_size: 32

He was able to work around the issue by increasing server_names_hash_bucket_size to 64 in nginx.conf.
#### Impact

No Ellis UI.
#### Release and environment

Seen on a recent AIO OVF.
#### Steps to reproduce

This happens when the local_ip, public_ip, and public_hostname are set to the same value on the node. Ellis generates a configuration file which includes each of these as a server name.

This explains the first two logs. However it may be that fixing this does not fix the server_names_hash_bucket_size issue.

**Comment by bossmc** [comment]
From the nginx docs (http://nginx.org/en/docs/http/server_names.html)

> If a large number of server names are defined, or unusually long server names are defined, tuning the server_names_hash_max_size and server_names_hash_bucket_size directives at the http level may become necessary. The default value of the server_names_hash_bucket_size directive may be equal to 32, or 64, or another value, depending on CPU cache line size. If the default value is 32 and server name is defined as “too.long.server.name.example.org” then nginx will fail to start and display the error message:

    could not build the server_names_hash,
    you should increase server_names_hash_bucket_size: 32

> In this case, the directive value should be increased to the next power of two:

    http {
        server_names_hash_bucket_size  64;
        ...

Suggesting that the issue here is that there's an entry in one of the `active-sites` config files that has a hostname over 32 characters long.

**Comment by chris-elford-metaswitch** [comment]
I agree. It would be nice to fix the conflict error messages which show up, but the real issue is the bucket size. Can we do something better to tune Nginx to the right value?

**Comment by lexplua** [comment]
> Can we do something better to tune Nginx to the right value?
According to nginx docs, it should be 2^n value. 64 enough for me.

**Comment by rkd-msw** [comment]
Fixed by https://github.com/Metaswitch/clearwater-nginx/pull/36, I think.
