### ISSUE TITLE
Clearwater-live-test hits 502 Bad Gateway error 

### ISSUE THREAD

**Issue by MatMeredith** [Metaswitch/ellis#174]
Seen running Clearwater-live-test against Clearwater release Diglett on cw-ngv.com.   Every time the live tests run they conclude with 502 Bad Gateway error reponse from Ellis.   Impact unknown.

-------------

rake test['cw-ngv.com'] ELLIS_API_KEY=<snip> TESTS="Basic Call*" TRANSPORT=UDP

Basic Call - Mainline (UDP) - (6505550020, 6505550070) Passed
Basic Call - Tel URIs (UDP) - (6505550063, 6505550030) Passed
Basic Call - Unknown number (UDP) - (6505550034, 6505550079) Passed
Basic Call - Rejected by remote endpoint (UDP) - (6505550029, 6505550009) Passed
Basic Call - Messages - Pager model (UDP) - (6505550026, 6505550040) Passed
Basic Call - Pracks (UDP) - (6505550020, 6505550069) Passed
502 Bad Gateway
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:746:in `start'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
/home/ubuntu/clearwater-live-test/lib/ellis.rb:57:in `destroy_leaked_numbers'
/home/ubuntu/clearwater-live-test/lib/live-test.rb:51:in `run_tests'
/home/ubuntu/clearwater-live-test/Rakefile:39:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/rake:23:in `load'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/rake:23:in `<main>'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'

**Comment by rkd-msw** [comment]
This is because of this error, from the Ellis error logs:

```
31-05-2016 08:23:40.124 UTC WARNING utils.py:78: Non-OK HTTP response. HTTPResponse(code=404,request_time=0.011878013610839844,buffer=<_io.BytesIO object at 0x7fe6260c8950>,_body=None,time_info={},request=<tornado.httpclient.HTTPRequest object at 0x7fe626086c90>,effective_url='http://hs.cw-ngv.com:8889/public/sip%3A%2B15108580277%40cw-ngv.com/associated_private_ids',headers={'Content-Length': '95', 'Content-Encoding': 'gzip', 'Server': 'nginx/1.4.6 (Ubuntu)', 'Connection': 'close', 'Date': 'Tue, 31 May 2016 08:23:40 GMT', 'Content-Type': 'application/json'},error=HTTPError('HTTP 404: Not Found',))
31-05-2016 08:23:40.124 UTC WARNING numbers.py:114: Failed to fetch private identities from homestead
31-05-2016 08:23:40.125 UTC ERROR web.py:1447: 502 GET /accounts/live.tests@example.com/numbers (0.0.0.0) 15.15ms
```

That is:

- as part of deleting sip:+15108580277@cw-ngv.com, we query homestead-prov for its associated private identities
- homestead-prov doesn't know anything about it and returns 404
- we [call forward_error](https://github.com/Metaswitch/ellis/blob/a719290d7310cc3fae99596346a0cbd9f4f0ccb5/src/metaswitch/ellis/api/numbers.py#L115) in that case, which [returns 502](https://github.com/Metaswitch/ellis/blob/f81ba4d25362ca7e00972de9435803046020fbf7/src/metaswitch/ellis/api/_base.py#L290)

I've grepped for '580277' in the logs, but they don't suggest an obvious sequence of events that could lead to this bug:

```
/var/log/ellis/ellis-1_20160329T110000Z.txt:29-03-2016 11:40:34.757 UTC INFO web.py:1447: 200 DELETE /accounts/live.tests@example.com/numbers/sip%3A%2B15108580277%40cw-ngv.com (0.0.0.0) 64.57ms
/var/log/ellis/ellis-1_20160329T120000Z.txt:29-03-2016 12:12:04.550 UTC INFO web.py:1447: 200 PUT /accounts/live.tests@example.com/numbers/sip%3A%2B15108580277%40cw-ngv.com/simservs (0.0.0.0) 6.84ms
/var/log/ellis/ellis-1_20160420T100000Z.txt:20-04-2016 10:39:58.394 UTC WARNING utils.py:78: Non-OK HTTP response. HTTPResponse(code=404,request_time=0.006556034088134766,buffer=<_io.BytesIO object at 0x7f624e81dd10>,_body=None,time_info={},request=<tornado.httpclient.HTTPRequest object at 0x7f624e7935d0>,effective_url='http://hs.cw-ngv.com:8889/public/sip%3A%2B15108580277%40cw-ngv.com/associated_private_ids',headers={'Content-Length': '95', 'Content-Encoding': 'gzip', 'Server': 'nginx/1.4.6 (Ubuntu)', 'Connection': 'close', 'Date': 'Wed, 20 Apr 2016 10:39:58 GMT', 'Content-Type': 'application/json'},error=HTTPError('HTTP 404: Not Found',))
/var/log/ellis/ellis-1_20160420T100000Z.txt:20-04-2016 10:40:07.430 UTC WARNING utils.py:78: Non-OK HTTP response. HTTPResponse(code=404,request_time=0.005581855773925781,buffer=<_io.BytesIO object at 0x7f624e81db30>,_body=None,time_info={},request=<tornado.httpclient.HTTPRequest object at 0x7f624e793c90>,effective_url='http://hs.cw-ngv.com:8889/public/sip%3A%2B15108580277%40cw-ngv.com/associated_private_ids',headers={'Content-Length': '95', 'Content-Encoding': 'gzip', 'Server': 'nginx/1.4.6 (Ubuntu)', 'Connection': 'close', 'Date': 'Wed, 20 Apr 2016 10:40:07 GMT', 'Content-Type': 'application/json'},error=HTTPError('HTTP 404: Not Found',))
```

Solutions:

* We can stop this error just by removing 'sip:+15108580277@cw-ngv.com' from Ellis's database, so it stops trying and failing to delete it
* We could log out, at INFO level, the requests we make to Homer and homestead-prov (instead of just logging failed responses) - this might make it easier to spot a sequence of events that lead to this bad state
* Ellis could auto-delete bad numbers in this case (i.e. automating bullet point 1) - this risks silently leaking data in Homer and Homestead, but we know Ellis is demo-quality-only, and it's probably more important to have an error-free user experience than a rock-solid provisioning system. (It's also not obvious that a user could do better.)

**Comment by rkd-msw** [comment]
(Should we also only run one Ellis process, so we don't have to look through the ellis and ellis-1 logs for these issues?)

**Comment by rkd-msw** [comment]
The 502 has this body - could the live tests use it to give better diagnostics?

```
{"status": 502, "message": "Bad Gateway", "reason": "Upstream request failed", "detail": {"Upstream error": "HTTP 404: Not Found"}, "error": true}
```
