### ISSUE TITLE
Homestead-prov's list_backups.sh script actually just lists everything in the directory you pass it

### ISSUE THREAD

**Issue by AME2** [Metaswitch/ellis#207]
I was doing some testing of Homestead-prov's backup and restore procedure and noticed that list_backups.sh prints everything out in the directory you pass it:

```
clearwater@ame2-homestead-1:~$ sudo mkdir /usr/share/clearwater/homestead/backup/backups/provisioning/not_a_backup

clearwater@ame2-homestead-1:~$ sudo /usr/share/clearwater/bin/run-in-signaling-namespace /usr/share/clearwater/bin/list_backups.sh homestead_provisioning
No backup directory specified, defaulting to /usr/share/clearwater/homestead/backup/backups/provisioning
1486398951647
not_a_backup
```

You are allowed to change the backup directory as you make a backup. This means you could possibly put a backup in /tmp, running the list_backups.sh script pointing at /tmp gives you:

```
clearwater@ame2-homestead-1:~$ sudo /usr/share/clearwater/bin/run-in-signaling-namespace /usr/share/clearwater/bin/list_backups.sh homestead_provisioning /tm                                                                                p
Will look for backups in /tmp
bash.bashrc.cwc
clearwater-alarms
clearwater_management_namespace_socket
clearwater_signaling_namespace_socket
dnsmasg.default
homestead
homestead-http-mgmt-socket
hsperfdata_cassandra
hsperfdata_root
jna-1073564104
liblz4-java5288096666170012131.so
libnetty-transport-native-epoll2999666656398234213.so
local_config.cust
snappy-1.0.5.2-libsnappyjava.so
ssh-I5EmQpKtVp
stats0
tmp.SNqMY0Rvqv
tmp.x7Oa9OCIlc
vmware-root
```

I'm making this medium priority as there are deployments out in the Real-World using homestead-prov and this could leave us looking red faced. 

Seeing as list_backups does not gives you anything extra over ls we could remove this script along with the mentions of it in the docs.

**Comment by rkd-msw** [comment]
@AME2 - should this be in the clearwater-cassandra repository rather than ellis?

**Comment by AME2** [comment]
@rkd-msw Yes it should be, Ellis also has a do_backup.sh script but it is not the one mentioned in the issue above. Will close and move: https://github.com/Metaswitch/clearwater-cassandra/issues/130
