### ISSUE TITLE
API docs say JSON can be used for resources that don't support it

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/ellis#67]
In particular, creation of new accounts does not support the data being provided in JSON format. However, all the examples are in JSON format and the docs say "In most cases, POSTs support both JSON and URL-encoded data (URL-encoded data may not be supported for data that isn't "flat")".

**Comment by graemerobertson** [comment]
I haven't successfully been able to use the creating new accounts API, although comfortably the closest I've got is by using JSON format, so I'm not convinced this is a real issue.
