### ISSUE TITLE
API docs on redirect are wrong (and maybe we should do something different anyway)

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/ellis#71]
https://github.com/Metaswitch/ellis/blob/dev/docs/api.md#user-accounts (and elsewhere) says that if the client requests redirection, a 301 response is provided. This is incorrect - we give a 302 response (as this is a temporary redirect, not a permanent one).

However, 302 responses to POST requests are slightly ill-defined - browsers may or may not make a POST or GET request to the redirected path. HTTP/1.1 defines 303 (always GET) and 307 (always POST) instead. Changing to 307 would help us resolve https://github.com/Metaswitch/ellis/issues/18 (which is closed but not fixed), as we could only read the URL params when the request was POST, and ignore them if the page was bookmarked and a GET was subsequently made.

That's a nice-to-have, though - we could fix this just by updating the API docs to say 302.

**Comment by graemerobertson** [comment]
I'm intending to update the API docs to say 302 and close this issue. Feel free to open a new issue to cover the potential enhancement (please don't).
